### ISSUE TITLE
OPDS Catalog Support

### ISSUE THREAD

**Issue by matt-curtis** [hyphen-reader/hyphen#10]
- +Bulk Download of books

**Comment by ijudy** [comment]
OPDS (Open Publication Distribution System) (I confuse it too) is a nice feature. It makes it really convenient and easy to get new books.

**Comment by eskwayrd** [comment]
This is the enhancement I'm waiting for! Do you know when you might release 2.0?

**Comment by matt-curtis** [comment]
@eskwayrd The beta will be out in the coming 2 or 3 weeks, hopefully.

**Comment by gennaios** [comment]
I haven't tried it yet in the beta, though I do have some thoughts about the future. One possible ideal is similar to Photos or iTunes Match, everything in the cloud shows up, and tap to download and start reading. If one has a calibre or personal OEBPS catalog, what's preventing an app from treating it like cloud storage, indexing author/title/publisher/tag/rating,etc and making it easily searchable? Showing all in a library might be difficult unless one came up with a way to browse a huge collection, much like iTunes or Music, but an easy way to search, let's say if a particular catalog could be cached and updated at search time or regular interval, when one searched one's library, a list of local books first, and then a header, and then cloud books, so far, that's my ideal.

**Comment by matt-curtis** [comment]
@empedocle That's a cool suggestion. There are some technical implications of implementing something like that to be considered, but cool nonetheless. Separate issue?

**Comment by gennaios** [comment]
Sure I'll try to make an issue when I get a chance. Of the xml tree by author, tag, rating, etc, perhaps using the download URL as making files unique so one can collect metadata by parsing each part to gather the info. That seems like the only issue I can think of. Maybe caching images if desired.

**Comment by derekmcelfresh** [comment]
I'm in the beta, and while the OPDS feature seems to work with the preconfigured servers, it won't connect to my local OPDS server out of Calibre. I just get an error saying "Load Failed".

**Comment by matt-curtis** [comment]
@derekmcelfresh Hello Derek!

Here's a few tips to get it working:
1. Make sure you're on the same network as the computer running Calibre is.
2. The URL you give Hyphen should look something like `192.168.0.xxx:PORT/opds`. Where `PORT` is the port given in the Calibre Connect/Share menu.

Let me know if you still can't get it working.

**Comment by derekmcelfresh** [comment]
Ah ha. The /opds at the end is what was missing. For what it's worth, other readers I've used haven't required that line — is there documentation somewhere that this is a necessary step?

**Comment by derekmcelfresh** [comment]
Now that I've got OPDS working, is there a 'Download All' button that I'm just not seeing?

**Comment by matt-curtis** [comment]
Not every OPDS catalog URL is `http://host/opds`. There's no consistent standard or practice for what URL the OPDS catalog is under (be nice if there was!) In Calibre's case, it's under the `/opds` path.

There is not currently a 'Download All' option available for OPDS catalog listings.
