### ISSUE TITLE
Basic Access Authentication

### ISSUE THREAD

**Issue by rupa** [hyphen-reader/hyphen#13]
Thanks for this reader!

It seems that going to a page that requires (Basic) http auth hangs and doesn't pop up a means to enter user/pass.

For now, I'm able to use Safari, click on an epub, and "Open in".

Additionally, I tend to put my books in a single web-accessible directory - would be nice to be able to save that as a "bookmark" under "Add Books".

**Comment by matt-curtis** [comment]
Thanks for opening an issue for this, I'll look into it.

As far as bookmarking goes, the in-app browser does provide a way to bookmark sites. Let me know if that works for you.

**Comment by rupa** [comment]
Cool.

I did find that the in-app browser worked with the page if i used `http://USER:PASSWORD@domain.tld` format for the URL.

Took a few seconds to find the bookmarking functionality, that works fine.

I'm liking this reader a lot, OSX could really use this as well, especially with sync between IOS!

**Comment by matt-curtis** [comment]
Nice, glad the bookmarking functions worked. I'll have the authentication prompt issue fixed soon.

I'm excited about the possibilities on OS X as well! :)

**Comment by rupa** [comment]
A couple of issues with this implementation:

if I bookmark the page with the "normal" URL, I get prompted for the user/pass, but books then fail to download. This is because the server expects authentication info with each request.

Using the format above for the bookmark still works, and books will download, but I still get the user/pass dialog, although the information is now redundant.

**Comment by matt-curtis** [comment]
@rupa Do you have any examples of the kinds of HTTP Authentication-sites you visit? I'd like to test a few.

**Comment by rupa** [comment]
I've set up a demo at http://basic.rupa.co/

username test, password test

I've stuck a book in there so you can see how you have to pass the creds to download it as well.

basic auth isn't secure, so it's not widely used by professional sites - I use it just to keep my folder of books from being explicitly public, real security is not a big deal to me for this use case.

There's also digest auth to be aware of - https://en.wikipedia.org/wiki/Digest_access_authentication - i don't use it really, either i don't really care about security and use Basic, or i care, and use other methods entirely, but YMMV.

**Comment by matt-curtis** [comment]
Wow, thank you. I've tested it and all seems well, subsequent requests etc.

**Comment by rupa** [comment]
cool, I'll leave it there till this issue gets closed :)
