### ISSUE TITLE
brightness adjustment change?

### ISSUE THREAD

**Issue by rupa** [hyphen-reader/hyphen#16]
consider making brightness adjustment a two-finger or three-finger swipe? it's a nice feature but easy to trigger accidentally.

pro - less likely to adjust brightness when trying to turn a page.
con - less likely to discover this feature exists

:smile:

**Comment by matt-curtis** [comment]
Haha. What times do you find yourself accidentally triggering it? Any specific actions? I've actually lowered the sensitivity of it quite a bit.

**Comment by rupa** [comment]
I think maybe it's more sensitive at the low end of the brightness scale? I trigger it sometimes when turning pages.

**Comment by matt-curtis** [comment]
Hmm, I'll keep that in mind. I can't trigger it myself unless I'm swiping directly up and down.
