### ISSUE TITLE
Offer option to disable/reduce tap to turn page feature

### ISSUE THREAD

**Issue by matt-curtis** [hyphen-reader/hyphen#34]

**Comment by matthewwimer** [comment]
I'd love this as well. On the iPad mini, the area designated for this function is larger than feasible. In order to access the settings, I have to tap right in the middle of the screen, which while holding with one hand is a bit hard. I inadvertently turn pages all the time. Thank you!

**Comment by matt-curtis** [comment]
On the way :)

**Comment by matthewwimer** [comment]
Fantastic! I appreciate the quick response. I’ve tried a bunch of different readers on the ipad, and thus far yours is my favorite. Simple, easy to work with, customizes the things I want, and makes reading awesome!
