### ISSUE TITLE
Unable to access the pop up feature to add notes to a highlight on 6S+

### ISSUE THREAD

**Issue by theipadforpastors** [hyphen-reader/hyphen#42]
When I press and hold on a highlight in Hyphen on my 6S+, the highlight pulses for a second, then selects a words. No pop up for adding notes.
I thought maybe I was just not understanding how to add notes at first, but I tried it on my iPad Air 2 and it works just fine.

**Comment by matt-curtis** [comment]
Yikes. I wasn't aware of this issue, but I think it's force-touch related. I'm in the midst of investigating this to see if I can find the culprit! Thanks for opening an issue. As a workaround, you can edit/delete highlights from the book drawer, by swiping on it.

**Comment by theipadforpastors** [comment]
Problem persists with 3D Touch turned off, and also exists on my wife's 6S running 9.2.
I had already seen the highlights drawer, I really like it! And I do most reading on the iPad where the issue doesn't show up anyway. Not a serious problem for me, just wanted you to be aware.
