### ISSUE TITLE
Underline from a search selection is too short on the iPad

### ISSUE THREAD

**Issue by ijudy** [hyphen-reader/hyphen#48]
Doing a search and tapping on a selection brings me to a page with an ephemeral underline. This works fine for me on my iPhone, but not on my iPad. The underline needs to last longer, or maybe be a highlight, so I can locate it on my iPad. I have it set for 2-columns, so maybe that’s the reason. There’s just too much area to search to find that underline before it disappears, as it stands right now. Thanks.

**Comment by matt-curtis** [comment]
I've completely changed the 'found selection' animation in 2.0 in a way that I think fixes this problem. We'll see soon :)

**Comment by ijudy** [comment]
😊

Thanks!

Judy
