### ISSUE TITLE
Internal setting to lock portrait/landscape orientation within Hyphen

### ISSUE THREAD

**Issue by ijudy** [hyphen-reader/hyphen#50]
I request this for my iPad in particular. This is because if I set it globally to lock in portrait mode in Control Center and tip the screen to landscape mode to read, and then switch to another app, like Apple Music, it does not display properly, or I just want other apps to display in landscape mode when I switch to them from Hyphen. Thanks.

**Comment by matt-curtis** [comment]
This setting is available under the General tab in settings - Portrait, Landscape, Auto.

**Comment by ijudy** [comment]
I hadn’t seen it, but It’s not working on my iPad. Just tried it.

**Comment by matt-curtis** [comment]
Can you tell me what behavior you're seeing, exactly? Does it just straight ignore your setting? Also, what device and iOS version are you running?

**Comment by ijudy** [comment]
iPad Air 2, iOS 9.2.1

I want two long, tall columns. I hold the iPad in portrait mode with the book open and columns displayed properly. I tap on SETTINGS icon near the top of the page. I go to GENERAL/ROTATION MODE/PORTRAIT. I quit settings. I turn the iPad to landscape mode and the columns rotate with it. I was on GENERAL/ROTATION MODE/AUTOMATIC originally. I also tried GENERAL/ROTATION MODE/LANDSCAPE and it also rotated, so none seem to work. Still now, I am wondering if these settings are supposed to be the same as the rotation lock/unlock in the Control Center? Why do you need 3 choices when I think of it as a toggle (with 2 choices)?

Thanks!

Judy

**Comment by matt-curtis** [comment]
Thanks for the detailed walkthrough.

Hyphen provides 3 options for orientation lock - landscape, portrait, and auto. The default system orientation (as far as I know) only locks to portrait. The user may not want orientation locked to either landscape or portrait, but have the default behavior, which is interface orientation = device orientation. That's why the Auto setting is there.
