### ISSUE TITLE
Control Brightness Control Sensitivity / Disable

### ISSUE THREAD

**Issue by tthkbw** [hyphen-reader/hyphen#51]
I like being able to control brightness by swiping down on the display.

However, it creates a problem when using Hyphen on my iPhone. I hold the iPhone in my left hand and use my thumb in a swipe across the screen to turn the page. The natural motion is an arc starting low on the right of the screen and arcing upward and to the left. Sometimes, this motion is interpreted as a brightness change and the page doesn't turn but the brightness goes up. Interestingly, it is my experience that when a brightness change occurs, then the next swipe seems more likely to also be interpreted as a brightness change.

I am not an iOS programmer, but my experience tells me that there is probably some setting for gestures that allows gestures like this to be restricted in how accurate they must be. For example, for Hyphen to turn the page, it is not necessary to use a perfectly straight horizontal line swipe. I know that other readers, for example, are much more restrictive than Hyphen in interpreting the swipe left for page turning. It is one of the benefits of Hyphen that I don't have to contort my thumb swipe to work the way I want.

So, for me (and it is all about me, of course) I would prefer to have the brightness control be more restrictive so that a primarily right to left swipe that also moved vertically would not be misinterpreted as a vertical swipe. Since brightness control is a less used gesture, requiring more accuracy for that seems reasonable.

Alternatively, if there were a user option to turn off brightness control via gesture, that would also work.

Thanks,

Terry Brown

**Comment by matt-curtis** [comment]
Hello Terry,

I just tested this out. I've reworked gestures in 2.0, and this isn't a problem anymore, as the brightness control gesture is now a lot less forgiving. You can also disable it entirely, so there's that as well :)
