### ISSUE TITLE
iCloud sync

### ISSUE THREAD

**Issue by matthewwimer** [hyphen-reader/hyphen#53]
I realize you've got the Hyphenlink, but one thing I would like that would be cool is to have the entire library sync'd via iCloud (including notes, highlights, epub, location in book, etc). That way I can walk away from my iPad (where I do most of my reading), open my phone and pickup where I left off, then return back to my iPad and finish.

**Comment by matt-curtis** [comment]
Thanks for the feedback. This feature is expressed in #6.

**Comment by matthewwimer** [comment]
Oops! My bad. Thank you!
