### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by matt-curtis** [hyphen-reader/hyphen#6]
Library, Bookmarks, Highlights, Shelves, Reading Position.

**Comment by zachlatta** [comment]
If there's any way of syncing with Kindle, that would be _amazing_.

**Comment by matt-curtis** [comment]
That would be. Unfortunately I don't believe Amazon shares that data.

**Comment by rfog** [comment]
Syncing reading position between devices. Only that. Please.

**Comment by matt-curtis** [comment]
Hello @rfog, what is the difference to you? That is, what separates full-sync from only syncing reading position?

**Comment by rfog** [comment]
Sorry, I wrote it bad.

I mean that at least, implement reading position. If you implement sync all (library, etc), ok, but if you only are going to implement a thing, do it with reading position.

Other way, I've deleted al my Marvin's and purchased your app, in the wait you will implement at least reading position sync.

And I'm very happy your app is iPad Pro ready. However a 4 columns in landscape and 2 columns modes in portrait seems to be needed. Or left a blank part to make annotations.

**Comment by matt-curtis** [comment]
> I mean that at least, implement reading position. If you implement sync all (library, etc), ok, but if you only are going to implement a thing, do it with reading position.

Ah, I see. At the moment, the following will be synchronized: Library, Highlights, Bookmarks, Reading Position, Shelves.

> And I'm very happy your app is iPad Pro ready. However a 4 columns in landscape and 2 columns modes in portrait seems to be needed. Or left a blank part to make annotations.

Those are very interesting ideas, I like them! Hopefully I'll get a chance to consider this sometime in the future.
