### ISSUE TITLE
Very big text in footnotes (only in some books).

### ISSUE THREAD

**Issue by LeonardoLeiteCastro** [hyphen-reader/hyphen#63]
Hi, 

In some books, the footnotes´ text is so big.

Could you make it become smaller?

**Comment by matt-curtis** [comment]
Is this issue regarding the beta or current version?

**Comment by LeonardoLeiteCastro** [comment]
The current one (I gess it´s 1.1.1). I can check it later.

**Comment by matt-curtis** [comment]
You may want to try opening a book, then Settings > Publisher Styling > Font Size. Hyphen will then override the publisher's font size choices.

**Comment by LeonardoLeiteCastro** [comment]
I'll try to do it later. By now, I'm far from my iPad. Just got Hyphen´s paid version yesterday. Congratulations for the outstanding app!

**Comment by LeonardoLeiteCastro** [comment]
Hi,

I tried your tip, but it didn't work.

The font of the main text is OK. But the footnotes are still very big. 

I tried the same book in Marvin Classic, Marvin 3 and Bookari (Mantano). The epub file worked well with these three apps.

**Comment by matt-curtis** [comment]
Please send the ePub(s) in question to me at hyphenreader@gmail.com

**Comment by LeonardoLeiteCastro** [comment]
I've just sent, Matt.

Thanks a lot!

Leonardo.
