### ISSUE TITLE
Google Drive not working

### ISSUE THREAD

**Issue by mpvrana** [hyphen-reader/hyphen#75]
When trying to add Google Drive access to Hyphen, I receive the following error:

403. That’s an error.

Error: disallowed_useragent
This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

And then there's a link to:

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by matt-curtis** [comment]
Thanks for filing an issue :)

This has been since fixed in an update.
